name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apt install JQ
        run: sudo apt install -y jq
      - name: Run Get Find Pet By Status
        run: curl https://petstore.swagger.io/v2/pet/findByStatus?status=available >> output.json
      - name: Run extract JSON
        run: jq '.' output.json

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
